# Configuración GitHub Pages
exclude:
  - "*.Rmd"
  - "*.R" 
  - requirements.txt
  - "*.md"
  - README.md

# Solo procesar HTML
include:
  - "*.html"

# Configuración Jekyll
markdown: kramdown
theme: minima
