remote_theme: poole/hyde
exclude: ["*.Rmd", "*.R"]
markdown: kramdown

title: "Yelko Bejarano"
tagline: "Data Scientist & Biostatistician"
description: "Portfolio de Análisis de Datos"
baseurl: ""
url: "https://yelkob.github.io/Portfolio"

# Hyde settings
hyde:
  theme: "theme-base-08"  # Color scheme
